### ISSUE TITLE
Missing environment.yml

### ISSUE THREAD

**Issue by mwhamgenomics** [ggrimes/nf-training#1]
Working through the Setup page of  carpentries-incubator/workflows-nextflow, the step after downloading the training material mentions an environment.yml file that doesn't exist:
```
# Training material
Download the training material copy & pasting the following command in the terminal:

    $ git clone https://github.com/ggrimes/nf-training
    $ cd nf-training

# Training software
The simplest way to install the software for this course is using conda.
To install conda see [here](link).

To create the training environment run:

    conda env create -f environment.yml

...
```

**Comment by kirito002** [comment]
I have the same problem as you, it seems that the authorities are not aware of this small but important problem, I found it under `/scripts/rnaseq_pipeline/environment.yml. `
It feels the same, the environment is named differently. I'll just press this one to install it.

**Comment by IsabelFE** [comment]
I have the same issue

**Comment by amcdavid** [comment]
I also needed to edit `nextflow.config` to point conda environment path.  Could use `$HOME` rather than hardcoding `/home/training` and stipulate the conda environment name with `conda env create -n nf-training -f scripts/rnaseq_pipeline/environment.yml` so this would work out of the box for most conda setups.
